### ISSUE TITLE
Pausing the game pauses music player

### ISSUE THREAD

**Issue by strayobject** [rec0de/2107#1]
To replicate, launch 'media' app and start music playback.

With music playing launch 2107, start playing and press 'pause' button.

Output from 'media' is stopped.

This is particularly annoying as dropping off a building also stops playback.

Game v0.1.5
SFOS v1.1.9.28

**Comment by rec0de** [comment]
Thanks for noticing!
For me playback only stops sometimes in about 50% of all restart / pause operations.
I'll try to fix it asap.

**Comment by rec0de** [comment]
Fixed with 08dd611.
